### ISSUE TITLE
Upgrade node-sass version

### ISSUE THREAD

**Issue by RashakDude** [CatsInTech/GitHub-ReadMe#22]
Hi @praveenscience, node-sass version is deprecated. This needs to be upgraded so that the application can be run in local.

**Comment by praveenscience** [comment]
@RashakDude Ah, I checked everything seems working perfectly fine... What's the node-sass version is right? I see some discussion around that is happening. Can you confirm me the working version please? So that I can test it on all Windows, Mac and Linux before doing anything?

![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/1830380/0a430f54-bb61-4612-8a81-e079fc7225ac)

**Comment by gurjeetsinghvirdee** [comment]
Hey @praveenscience assign me for this & don't add gssoc labels I'm just doing some open source ❤️

**Comment by praveenscience** [comment]
@gurjeetsinghvirdee Go for it! <3
